// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSHeshFLXsfqbIY7LGlRUx8RJyki8ZyFU',
    appId: '1:475664841613:web:a2ae1e0eb7a56b75ec5bc4',
    messagingSenderId: '475664841613',
    projectId: 'swiftshop-5e2eb',
    authDomain: 'swiftshop-5e2eb.firebaseapp.com',
    storageBucket: 'swiftshop-5e2eb.appspot.com',
    measurementId: 'G-ET0LHX8P05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4uR5_QlrE5TwAPReT-bN93MH2SvH1HOM',
    appId: '1:475664841613:android:bb3894c3094a582cec5bc4',
    messagingSenderId: '475664841613',
    projectId: 'swiftshop-5e2eb',
    storageBucket: 'swiftshop-5e2eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx5QbwFITJj5PcDld9jtbtOcF0rJTRPQ4',
    appId: '1:475664841613:ios:74e3912cc1fa11abec5bc4',
    messagingSenderId: '475664841613',
    projectId: 'swiftshop-5e2eb',
    storageBucket: 'swiftshop-5e2eb.appspot.com',
    iosBundleId: 'com.example.swiftshopApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx5QbwFITJj5PcDld9jtbtOcF0rJTRPQ4',
    appId: '1:475664841613:ios:74e3912cc1fa11abec5bc4',
    messagingSenderId: '475664841613',
    projectId: 'swiftshop-5e2eb',
    storageBucket: 'swiftshop-5e2eb.appspot.com',
    iosBundleId: 'com.example.swiftshopApplication',
  );
}
